#if UNITY_EDITOR

// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: resight/engine/rho/entities/entity-msgs.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Rho.Entities.Proto {

  /// <summary>Holder for reflection information generated from resight/engine/rho/entities/entity-msgs.proto</summary>
  public static partial class EntityMsgsReflection {

#region Descriptor
    /// <summary>File descriptor for resight/engine/rho/entities/entity-msgs.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EntityMsgsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci1yZXNpZ2h0L2VuZ2luZS9yaG8vZW50aXRpZXMvZW50aXR5LW1zZ3MucHJv",
            "dG8SEnJoby5lbnRpdGllcy5wcm90byJYCgVQb3NlMxIJCgF4GAEgASgCEgkK",
            "AXkYAiABKAISCQoBehgDIAEoAhIKCgJxeBgEIAEoAhIKCgJxeRgFIAEoAhIK",
            "CgJxehgGIAEoAhIKCgJxdxgHIAEoAiLRAQoLVXNlck1lc3NhZ2USNwoMZW50",
            "aXR5X2V2ZW50GAEgASgLMh8ucmhvLmVudGl0aWVzLnByb3RvLkVudGl0eUV2",
            "ZW50SAASPgoQbWVzaF9ibG9ja19ldmVudBgCIAEoCzIiLnJoby5lbnRpdGll",
            "cy5wcm90by5NZXNoQmxvY2tFdmVudEgAEkAKEW1lc2hfYmxvY2tfZXZlbnRz",
            "GAMgASgLMiMucmhvLmVudGl0aWVzLnByb3RvLk1lc2hCbG9ja0V2ZW50c0gA",
            "QgcKBXZhbHVlIjsKBE5vZGUSCgoCaWQYASABKAQSJwoEcG9zZRgCIAEoCzIZ",
            "LnJoby5lbnRpdGllcy5wcm90by5Qb3NlMyJJCgxWaXNpYmxlTm9kZXMSEAoI",
            "c3BhY2VfaWQYASABKAQSJwoFbm9kZXMYAiADKAsyGC5yaG8uZW50aXRpZXMu",
            "cHJvdG8uTm9kZSLrAgoLRW50aXR5RXZlbnQSQwoKZXZlbnRfdHlwZRgBIAEo",
            "DjIvLnJoby5lbnRpdGllcy5wcm90by5FbnRpdHlFdmVudC5FbnRpdHlFdmVu",
            "dFR5cGUSNAoCaWQYAiABKAsyKC5yaG8uZW50aXRpZXMucHJvdG8uRW50aXR5",
            "RXZlbnQuRW50aXR5SUQSJwoEcG9zZRgDIAEoCzIZLnJoby5lbnRpdGllcy5w",
            "cm90by5Qb3NlMxIMCgRkYXRhGAQgASgMEg8KB3ZlcnNpb24YBSABKAUaLgoI",
            "RW50aXR5SUQSDwoHdXNlcl9pZBgBIAEoCRIRCglwYXJlbnRfaWQYAiABKAMi",
            "aQoPRW50aXR5RXZlbnRUeXBlEhAKDEVOVElUWV9BRERFRBAAEhIKDkVOVElU",
            "WV9SRU1PVkVEEAESFwoTRU5USVRZX1BPU0VfVVBEQVRFRBACEhcKE0VOVElU",
            "WV9EQVRBX1VQREFURUQQAyL+AQoOTWVzaEJsb2NrRXZlbnQSEQoJYW5jaG9y",
            "X2lkGAEgASgEEhAKCGJsb2NrX2lkGAIgASgEEjoKCHBvc2l0aW9uGAMgASgL",
            "MigucmhvLmVudGl0aWVzLnByb3RvLk1lc2hCbG9ja0V2ZW50LlZlYzNmEjgK",
            "BmV4dGVudBgEIAEoCzIoLnJoby5lbnRpdGllcy5wcm90by5NZXNoQmxvY2tF",
            "dmVudC5WZWMzZhITCgt2ZXJ0ZXhfZGF0YRgFIAMoAhISCgppbmRleF9kYXRh",
            "GAYgAygNGigKBVZlYzNmEgkKAXgYASABKAISCQoBeRgCIAEoAhIJCgF6GAMg",
            "ASgCIk8KD01lc2hCbG9ja0V2ZW50cxI8ChBtZXNoX2Jsb2NrX2V2ZW50GAEg",
            "AygLMiIucmhvLmVudGl0aWVzLnByb3RvLk1lc2hCbG9ja0V2ZW50QgJIA2IG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Rho.Entities.Proto.Pose3), global::Rho.Entities.Proto.Pose3.Parser, new[]{ "X", "Y", "Z", "Qx", "Qy", "Qz", "Qw" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Rho.Entities.Proto.UserMessage), global::Rho.Entities.Proto.UserMessage.Parser, new[]{ "EntityEvent", "MeshBlockEvent", "MeshBlockEvents" }, new[]{ "Value" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Rho.Entities.Proto.Node), global::Rho.Entities.Proto.Node.Parser, new[]{ "Id", "Pose" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Rho.Entities.Proto.VisibleNodes), global::Rho.Entities.Proto.VisibleNodes.Parser, new[]{ "SpaceId", "Nodes" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Rho.Entities.Proto.EntityEvent), global::Rho.Entities.Proto.EntityEvent.Parser, new[]{ "EventType", "Id", "Pose", "Data", "Version" }, null, new[]{ typeof(global::Rho.Entities.Proto.EntityEvent.Types.EntityEventType) }, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Rho.Entities.Proto.EntityEvent.Types.EntityID), global::Rho.Entities.Proto.EntityEvent.Types.EntityID.Parser, new[]{ "UserId", "ParentId" }, null, null, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::Rho.Entities.Proto.MeshBlockEvent), global::Rho.Entities.Proto.MeshBlockEvent.Parser, new[]{ "AnchorId", "BlockId", "Position", "Extent", "VertexData", "IndexData" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Rho.Entities.Proto.MeshBlockEvent.Types.Vec3f), global::Rho.Entities.Proto.MeshBlockEvent.Types.Vec3f.Parser, new[]{ "X", "Y", "Z" }, null, null, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::Rho.Entities.Proto.MeshBlockEvents), global::Rho.Entities.Proto.MeshBlockEvents.Parser, new[]{ "MeshBlockEvent" }, null, null, null, null)
          }));
    }
#endregion

  }
#region Messages
  public sealed partial class Pose3 : pb::IMessage<Pose3>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
#endif
  {
    private static readonly pb::MessageParser<Pose3> _parser = new pb::MessageParser<Pose3>(() => new Pose3());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Pose3> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Rho.Entities.Proto.EntityMsgsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Pose3() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Pose3(Pose3 other) : this() {
      x_ = other.x_;
      y_ = other.y_;
      z_ = other.z_;
      qx_ = other.qx_;
      qy_ = other.qy_;
      qz_ = other.qz_;
      qw_ = other.qw_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Pose3 Clone() {
      return new Pose3(this);
    }

    /// <summary>Field number for the "x" field.</summary>
    public const int XFieldNumber = 1;
    private float x_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float X {
      get { return x_; }
      set {
        x_ = value;
      }
    }

    /// <summary>Field number for the "y" field.</summary>
    public const int YFieldNumber = 2;
    private float y_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Y {
      get { return y_; }
      set {
        y_ = value;
      }
    }

    /// <summary>Field number for the "z" field.</summary>
    public const int ZFieldNumber = 3;
    private float z_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Z {
      get { return z_; }
      set {
        z_ = value;
      }
    }

    /// <summary>Field number for the "qx" field.</summary>
    public const int QxFieldNumber = 4;
    private float qx_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Qx {
      get { return qx_; }
      set {
        qx_ = value;
      }
    }

    /// <summary>Field number for the "qy" field.</summary>
    public const int QyFieldNumber = 5;
    private float qy_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Qy {
      get { return qy_; }
      set {
        qy_ = value;
      }
    }

    /// <summary>Field number for the "qz" field.</summary>
    public const int QzFieldNumber = 6;
    private float qz_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Qz {
      get { return qz_; }
      set {
        qz_ = value;
      }
    }

    /// <summary>Field number for the "qw" field.</summary>
    public const int QwFieldNumber = 7;
    private float qw_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Qw {
      get { return qw_; }
      set {
        qw_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Pose3);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Pose3 other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(X, other.X)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Y, other.Y)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Z, other.Z)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Qx, other.Qx)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Qy, other.Qy)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Qz, other.Qz)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Qw, other.Qw)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (X != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(X);
      if (Y != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Y);
      if (Z != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Z);
      if (Qx != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Qx);
      if (Qy != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Qy);
      if (Qz != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Qz);
      if (Qw != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Qw);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
#else
      if (X != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(X);
      }
      if (Y != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Y);
      }
      if (Z != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Z);
      }
      if (Qx != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(Qx);
      }
      if (Qy != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(Qy);
      }
      if (Qz != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(Qz);
      }
      if (Qw != 0F) {
        output.WriteRawTag(61);
        output.WriteFloat(Qw);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
    }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (X != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(X);
      }
      if (Y != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Y);
      }
      if (Z != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Z);
      }
      if (Qx != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(Qx);
      }
      if (Qy != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(Qy);
      }
      if (Qz != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(Qz);
      }
      if (Qw != 0F) {
        output.WriteRawTag(61);
        output.WriteFloat(Qw);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
#endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (X != 0F) {
        size += 1 + 4;
      }
      if (Y != 0F) {
        size += 1 + 4;
      }
      if (Z != 0F) {
        size += 1 + 4;
      }
      if (Qx != 0F) {
        size += 1 + 4;
      }
      if (Qy != 0F) {
        size += 1 + 4;
      }
      if (Qz != 0F) {
        size += 1 + 4;
      }
      if (Qw != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Pose3 other) {
      if (other == null) {
        return;
      }
      if (other.X != 0F) {
        X = other.X;
      }
      if (other.Y != 0F) {
        Y = other.Y;
      }
      if (other.Z != 0F) {
        Z = other.Z;
      }
      if (other.Qx != 0F) {
        Qx = other.Qx;
      }
      if (other.Qy != 0F) {
        Qy = other.Qy;
      }
      if (other.Qz != 0F) {
        Qz = other.Qz;
      }
      if (other.Qw != 0F) {
        Qw = other.Qw;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 13: {
            X = input.ReadFloat();
            break;
          }
          case 21: {
            Y = input.ReadFloat();
            break;
          }
          case 29: {
            Z = input.ReadFloat();
            break;
          }
          case 37: {
            Qx = input.ReadFloat();
            break;
          }
          case 45: {
            Qy = input.ReadFloat();
            break;
          }
          case 53: {
            Qz = input.ReadFloat();
            break;
          }
          case 61: {
            Qw = input.ReadFloat();
            break;
          }
        }
      }
#endif
    }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 13: {
            X = input.ReadFloat();
            break;
          }
          case 21: {
            Y = input.ReadFloat();
            break;
          }
          case 29: {
            Z = input.ReadFloat();
            break;
          }
          case 37: {
            Qx = input.ReadFloat();
            break;
          }
          case 45: {
            Qy = input.ReadFloat();
            break;
          }
          case 53: {
            Qz = input.ReadFloat();
            break;
          }
          case 61: {
            Qw = input.ReadFloat();
            break;
          }
        }
      }
    }
#endif

  }

  /// <summary>
  //// - Wrapper over current user messages (hack)
  /// </summary>
  public sealed partial class UserMessage : pb::IMessage<UserMessage>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
#endif
  {
    private static readonly pb::MessageParser<UserMessage> _parser = new pb::MessageParser<UserMessage>(() => new UserMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UserMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Rho.Entities.Proto.EntityMsgsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UserMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UserMessage(UserMessage other) : this() {
      switch (other.ValueCase) {
        case ValueOneofCase.EntityEvent:
          EntityEvent = other.EntityEvent.Clone();
          break;
        case ValueOneofCase.MeshBlockEvent:
          MeshBlockEvent = other.MeshBlockEvent.Clone();
          break;
        case ValueOneofCase.MeshBlockEvents:
          MeshBlockEvents = other.MeshBlockEvents.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UserMessage Clone() {
      return new UserMessage(this);
    }

    /// <summary>Field number for the "entity_event" field.</summary>
    public const int EntityEventFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rho.Entities.Proto.EntityEvent EntityEvent {
      get { return valueCase_ == ValueOneofCase.EntityEvent ? (global::Rho.Entities.Proto.EntityEvent) value_ : null; }
      set {
        value_ = value;
        valueCase_ = value == null ? ValueOneofCase.None : ValueOneofCase.EntityEvent;
      }
    }

    /// <summary>Field number for the "mesh_block_event" field.</summary>
    public const int MeshBlockEventFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rho.Entities.Proto.MeshBlockEvent MeshBlockEvent {
      get { return valueCase_ == ValueOneofCase.MeshBlockEvent ? (global::Rho.Entities.Proto.MeshBlockEvent) value_ : null; }
      set {
        value_ = value;
        valueCase_ = value == null ? ValueOneofCase.None : ValueOneofCase.MeshBlockEvent;
      }
    }

    /// <summary>Field number for the "mesh_block_events" field.</summary>
    public const int MeshBlockEventsFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rho.Entities.Proto.MeshBlockEvents MeshBlockEvents {
      get { return valueCase_ == ValueOneofCase.MeshBlockEvents ? (global::Rho.Entities.Proto.MeshBlockEvents) value_ : null; }
      set {
        value_ = value;
        valueCase_ = value == null ? ValueOneofCase.None : ValueOneofCase.MeshBlockEvents;
      }
    }

    private object value_;
    /// <summary>Enum of possible cases for the "value" oneof.</summary>
    public enum ValueOneofCase {
      None = 0,
      EntityEvent = 1,
      MeshBlockEvent = 2,
      MeshBlockEvents = 3,
    }
    private ValueOneofCase valueCase_ = ValueOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ValueOneofCase ValueCase {
      get { return valueCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearValue() {
      valueCase_ = ValueOneofCase.None;
      value_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UserMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UserMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(EntityEvent, other.EntityEvent)) return false;
      if (!object.Equals(MeshBlockEvent, other.MeshBlockEvent)) return false;
      if (!object.Equals(MeshBlockEvents, other.MeshBlockEvents)) return false;
      if (ValueCase != other.ValueCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (valueCase_ == ValueOneofCase.EntityEvent) hash ^= EntityEvent.GetHashCode();
      if (valueCase_ == ValueOneofCase.MeshBlockEvent) hash ^= MeshBlockEvent.GetHashCode();
      if (valueCase_ == ValueOneofCase.MeshBlockEvents) hash ^= MeshBlockEvents.GetHashCode();
      hash ^= (int) valueCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
#else
      if (valueCase_ == ValueOneofCase.EntityEvent) {
        output.WriteRawTag(10);
        output.WriteMessage(EntityEvent);
      }
      if (valueCase_ == ValueOneofCase.MeshBlockEvent) {
        output.WriteRawTag(18);
        output.WriteMessage(MeshBlockEvent);
      }
      if (valueCase_ == ValueOneofCase.MeshBlockEvents) {
        output.WriteRawTag(26);
        output.WriteMessage(MeshBlockEvents);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
    }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (valueCase_ == ValueOneofCase.EntityEvent) {
        output.WriteRawTag(10);
        output.WriteMessage(EntityEvent);
      }
      if (valueCase_ == ValueOneofCase.MeshBlockEvent) {
        output.WriteRawTag(18);
        output.WriteMessage(MeshBlockEvent);
      }
      if (valueCase_ == ValueOneofCase.MeshBlockEvents) {
        output.WriteRawTag(26);
        output.WriteMessage(MeshBlockEvents);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
#endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (valueCase_ == ValueOneofCase.EntityEvent) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EntityEvent);
      }
      if (valueCase_ == ValueOneofCase.MeshBlockEvent) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MeshBlockEvent);
      }
      if (valueCase_ == ValueOneofCase.MeshBlockEvents) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MeshBlockEvents);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UserMessage other) {
      if (other == null) {
        return;
      }
      switch (other.ValueCase) {
        case ValueOneofCase.EntityEvent:
          if (EntityEvent == null) {
            EntityEvent = new global::Rho.Entities.Proto.EntityEvent();
          }
          EntityEvent.MergeFrom(other.EntityEvent);
          break;
        case ValueOneofCase.MeshBlockEvent:
          if (MeshBlockEvent == null) {
            MeshBlockEvent = new global::Rho.Entities.Proto.MeshBlockEvent();
          }
          MeshBlockEvent.MergeFrom(other.MeshBlockEvent);
          break;
        case ValueOneofCase.MeshBlockEvents:
          if (MeshBlockEvents == null) {
            MeshBlockEvents = new global::Rho.Entities.Proto.MeshBlockEvents();
          }
          MeshBlockEvents.MergeFrom(other.MeshBlockEvents);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Rho.Entities.Proto.EntityEvent subBuilder = new global::Rho.Entities.Proto.EntityEvent();
            if (valueCase_ == ValueOneofCase.EntityEvent) {
              subBuilder.MergeFrom(EntityEvent);
            }
            input.ReadMessage(subBuilder);
            EntityEvent = subBuilder;
            break;
          }
          case 18: {
            global::Rho.Entities.Proto.MeshBlockEvent subBuilder = new global::Rho.Entities.Proto.MeshBlockEvent();
            if (valueCase_ == ValueOneofCase.MeshBlockEvent) {
              subBuilder.MergeFrom(MeshBlockEvent);
            }
            input.ReadMessage(subBuilder);
            MeshBlockEvent = subBuilder;
            break;
          }
          case 26: {
            global::Rho.Entities.Proto.MeshBlockEvents subBuilder = new global::Rho.Entities.Proto.MeshBlockEvents();
            if (valueCase_ == ValueOneofCase.MeshBlockEvents) {
              subBuilder.MergeFrom(MeshBlockEvents);
            }
            input.ReadMessage(subBuilder);
            MeshBlockEvents = subBuilder;
            break;
          }
        }
      }
#endif
    }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::Rho.Entities.Proto.EntityEvent subBuilder = new global::Rho.Entities.Proto.EntityEvent();
            if (valueCase_ == ValueOneofCase.EntityEvent) {
              subBuilder.MergeFrom(EntityEvent);
            }
            input.ReadMessage(subBuilder);
            EntityEvent = subBuilder;
            break;
          }
          case 18: {
            global::Rho.Entities.Proto.MeshBlockEvent subBuilder = new global::Rho.Entities.Proto.MeshBlockEvent();
            if (valueCase_ == ValueOneofCase.MeshBlockEvent) {
              subBuilder.MergeFrom(MeshBlockEvent);
            }
            input.ReadMessage(subBuilder);
            MeshBlockEvent = subBuilder;
            break;
          }
          case 26: {
            global::Rho.Entities.Proto.MeshBlockEvents subBuilder = new global::Rho.Entities.Proto.MeshBlockEvents();
            if (valueCase_ == ValueOneofCase.MeshBlockEvents) {
              subBuilder.MergeFrom(MeshBlockEvents);
            }
            input.ReadMessage(subBuilder);
            MeshBlockEvents = subBuilder;
            break;
          }
        }
      }
    }
#endif

  }

  /// <summary>
  //// - Anchors (temporary hack)
  /// </summary>
  public sealed partial class Node : pb::IMessage<Node>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
#endif
  {
    private static readonly pb::MessageParser<Node> _parser = new pb::MessageParser<Node>(() => new Node());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Node> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Rho.Entities.Proto.EntityMsgsReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Node() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Node(Node other) : this() {
      id_ = other.id_;
      pose_ = other.pose_ != null ? other.pose_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Node Clone() {
      return new Node(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private ulong id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "pose" field.</summary>
    public const int PoseFieldNumber = 2;
    private global::Rho.Entities.Proto.Pose3 pose_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rho.Entities.Proto.Pose3 Pose {
      get { return pose_; }
      set {
        pose_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Node);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Node other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (!object.Equals(Pose, other.Pose)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0UL) hash ^= Id.GetHashCode();
      if (pose_ != null) hash ^= Pose.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
#else
      if (Id != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(Id);
      }
      if (pose_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Pose);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
    }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(Id);
      }
      if (pose_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Pose);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
#endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Id);
      }
      if (pose_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Pose);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Node other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0UL) {
        Id = other.Id;
      }
      if (other.pose_ != null) {
        if (pose_ == null) {
          Pose = new global::Rho.Entities.Proto.Pose3();
        }
        Pose.MergeFrom(other.Pose);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadUInt64();
            break;
          }
          case 18: {
            if (pose_ == null) {
              Pose = new global::Rho.Entities.Proto.Pose3();
            }
            input.ReadMessage(Pose);
            break;
          }
        }
      }
#endif
    }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadUInt64();
            break;
          }
          case 18: {
            if (pose_ == null) {
              Pose = new global::Rho.Entities.Proto.Pose3();
            }
            input.ReadMessage(Pose);
            break;
          }
        }
      }
    }
#endif

  }

  public sealed partial class VisibleNodes : pb::IMessage<VisibleNodes>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
#endif
  {
    private static readonly pb::MessageParser<VisibleNodes> _parser = new pb::MessageParser<VisibleNodes>(() => new VisibleNodes());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<VisibleNodes> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Rho.Entities.Proto.EntityMsgsReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VisibleNodes() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VisibleNodes(VisibleNodes other) : this() {
      spaceId_ = other.spaceId_;
      nodes_ = other.nodes_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VisibleNodes Clone() {
      return new VisibleNodes(this);
    }

    /// <summary>Field number for the "space_id" field.</summary>
    public const int SpaceIdFieldNumber = 1;
    private ulong spaceId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong SpaceId {
      get { return spaceId_; }
      set {
        spaceId_ = value;
      }
    }

    /// <summary>Field number for the "nodes" field.</summary>
    public const int NodesFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Rho.Entities.Proto.Node> _repeated_nodes_codec
        = pb::FieldCodec.ForMessage(18, global::Rho.Entities.Proto.Node.Parser);
    private readonly pbc::RepeatedField<global::Rho.Entities.Proto.Node> nodes_ = new pbc::RepeatedField<global::Rho.Entities.Proto.Node>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Rho.Entities.Proto.Node> Nodes {
      get { return nodes_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as VisibleNodes);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(VisibleNodes other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SpaceId != other.SpaceId) return false;
      if(!nodes_.Equals(other.nodes_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SpaceId != 0UL) hash ^= SpaceId.GetHashCode();
      hash ^= nodes_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
#else
      if (SpaceId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(SpaceId);
      }
      nodes_.WriteTo(output, _repeated_nodes_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
    }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SpaceId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(SpaceId);
      }
      nodes_.WriteTo(ref output, _repeated_nodes_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
#endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SpaceId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(SpaceId);
      }
      size += nodes_.CalculateSize(_repeated_nodes_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(VisibleNodes other) {
      if (other == null) {
        return;
      }
      if (other.SpaceId != 0UL) {
        SpaceId = other.SpaceId;
      }
      nodes_.Add(other.nodes_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SpaceId = input.ReadUInt64();
            break;
          }
          case 18: {
            nodes_.AddEntriesFrom(input, _repeated_nodes_codec);
            break;
          }
        }
      }
#endif
    }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SpaceId = input.ReadUInt64();
            break;
          }
          case 18: {
            nodes_.AddEntriesFrom(ref input, _repeated_nodes_codec);
            break;
          }
        }
      }
    }
#endif

  }

  /// <summary>
  //// - Entities (temporary hack)
  /// </summary>
  public sealed partial class EntityEvent : pb::IMessage<EntityEvent>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
#endif
  {
    private static readonly pb::MessageParser<EntityEvent> _parser = new pb::MessageParser<EntityEvent>(() => new EntityEvent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EntityEvent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Rho.Entities.Proto.EntityMsgsReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EntityEvent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EntityEvent(EntityEvent other) : this() {
      eventType_ = other.eventType_;
      id_ = other.id_ != null ? other.id_.Clone() : null;
      pose_ = other.pose_ != null ? other.pose_.Clone() : null;
      data_ = other.data_;
      version_ = other.version_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EntityEvent Clone() {
      return new EntityEvent(this);
    }

    /// <summary>Field number for the "event_type" field.</summary>
    public const int EventTypeFieldNumber = 1;
    private global::Rho.Entities.Proto.EntityEvent.Types.EntityEventType eventType_ = global::Rho.Entities.Proto.EntityEvent.Types.EntityEventType.EntityAdded;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rho.Entities.Proto.EntityEvent.Types.EntityEventType EventType {
      get { return eventType_; }
      set {
        eventType_ = value;
      }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 2;
    private global::Rho.Entities.Proto.EntityEvent.Types.EntityID id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rho.Entities.Proto.EntityEvent.Types.EntityID Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "pose" field.</summary>
    public const int PoseFieldNumber = 3;
    private global::Rho.Entities.Proto.Pose3 pose_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rho.Entities.Proto.Pose3 Pose {
      get { return pose_; }
      set {
        pose_ = value;
      }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 4;
    private pb::ByteString data_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Data {
      get { return data_; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "version" field.</summary>
    public const int VersionFieldNumber = 5;
    private int version_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Version {
      get { return version_; }
      set {
        version_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EntityEvent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EntityEvent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EventType != other.EventType) return false;
      if (!object.Equals(Id, other.Id)) return false;
      if (!object.Equals(Pose, other.Pose)) return false;
      if (Data != other.Data) return false;
      if (Version != other.Version) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (EventType != global::Rho.Entities.Proto.EntityEvent.Types.EntityEventType.EntityAdded) hash ^= EventType.GetHashCode();
      if (id_ != null) hash ^= Id.GetHashCode();
      if (pose_ != null) hash ^= Pose.GetHashCode();
      if (Data.Length != 0) hash ^= Data.GetHashCode();
      if (Version != 0) hash ^= Version.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
#else
      if (EventType != global::Rho.Entities.Proto.EntityEvent.Types.EntityEventType.EntityAdded) {
        output.WriteRawTag(8);
        output.WriteEnum((int) EventType);
      }
      if (id_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Id);
      }
      if (pose_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Pose);
      }
      if (Data.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(Data);
      }
      if (Version != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Version);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
    }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (EventType != global::Rho.Entities.Proto.EntityEvent.Types.EntityEventType.EntityAdded) {
        output.WriteRawTag(8);
        output.WriteEnum((int) EventType);
      }
      if (id_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Id);
      }
      if (pose_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Pose);
      }
      if (Data.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(Data);
      }
      if (Version != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Version);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
#endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (EventType != global::Rho.Entities.Proto.EntityEvent.Types.EntityEventType.EntityAdded) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) EventType);
      }
      if (id_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Id);
      }
      if (pose_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Pose);
      }
      if (Data.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Data);
      }
      if (Version != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Version);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EntityEvent other) {
      if (other == null) {
        return;
      }
      if (other.EventType != global::Rho.Entities.Proto.EntityEvent.Types.EntityEventType.EntityAdded) {
        EventType = other.EventType;
      }
      if (other.id_ != null) {
        if (id_ == null) {
          Id = new global::Rho.Entities.Proto.EntityEvent.Types.EntityID();
        }
        Id.MergeFrom(other.Id);
      }
      if (other.pose_ != null) {
        if (pose_ == null) {
          Pose = new global::Rho.Entities.Proto.Pose3();
        }
        Pose.MergeFrom(other.Pose);
      }
      if (other.Data.Length != 0) {
        Data = other.Data;
      }
      if (other.Version != 0) {
        Version = other.Version;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            EventType = (global::Rho.Entities.Proto.EntityEvent.Types.EntityEventType) input.ReadEnum();
            break;
          }
          case 18: {
            if (id_ == null) {
              Id = new global::Rho.Entities.Proto.EntityEvent.Types.EntityID();
            }
            input.ReadMessage(Id);
            break;
          }
          case 26: {
            if (pose_ == null) {
              Pose = new global::Rho.Entities.Proto.Pose3();
            }
            input.ReadMessage(Pose);
            break;
          }
          case 34: {
            Data = input.ReadBytes();
            break;
          }
          case 40: {
            Version = input.ReadInt32();
            break;
          }
        }
      }
#endif
    }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            EventType = (global::Rho.Entities.Proto.EntityEvent.Types.EntityEventType) input.ReadEnum();
            break;
          }
          case 18: {
            if (id_ == null) {
              Id = new global::Rho.Entities.Proto.EntityEvent.Types.EntityID();
            }
            input.ReadMessage(Id);
            break;
          }
          case 26: {
            if (pose_ == null) {
              Pose = new global::Rho.Entities.Proto.Pose3();
            }
            input.ReadMessage(Pose);
            break;
          }
          case 34: {
            Data = input.ReadBytes();
            break;
          }
          case 40: {
            Version = input.ReadInt32();
            break;
          }
        }
      }
    }
#endif

#region Nested types
    /// <summary>Container for nested types declared in the EntityEvent message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum EntityEventType {
        [pbr::OriginalName("ENTITY_ADDED")] EntityAdded = 0,
        [pbr::OriginalName("ENTITY_REMOVED")] EntityRemoved = 1,
        [pbr::OriginalName("ENTITY_POSE_UPDATED")] EntityPoseUpdated = 2,
        [pbr::OriginalName("ENTITY_DATA_UPDATED")] EntityDataUpdated = 3,
      }

      public sealed partial class EntityID : pb::IMessage<EntityID>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
#endif
      {
        private static readonly pb::MessageParser<EntityID> _parser = new pb::MessageParser<EntityID>(() => new EntityID());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<EntityID> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Rho.Entities.Proto.EntityEvent.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public EntityID() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public EntityID(EntityID other) : this() {
          userId_ = other.userId_;
          parentId_ = other.parentId_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public EntityID Clone() {
          return new EntityID(this);
        }

        /// <summary>Field number for the "user_id" field.</summary>
        public const int UserIdFieldNumber = 1;
        private string userId_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string UserId {
          get { return userId_; }
          set {
            userId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "parent_id" field.</summary>
        public const int ParentIdFieldNumber = 2;
        private long parentId_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public long ParentId {
          get { return parentId_; }
          set {
            parentId_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as EntityID);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(EntityID other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (UserId != other.UserId) return false;
          if (ParentId != other.ParentId) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (UserId.Length != 0) hash ^= UserId.GetHashCode();
          if (ParentId != 0L) hash ^= ParentId.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
#else
          if (UserId.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(UserId);
          }
          if (ParentId != 0L) {
            output.WriteRawTag(16);
            output.WriteInt64(ParentId);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (UserId.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(UserId);
          }
          if (ParentId != 0L) {
            output.WriteRawTag(16);
            output.WriteInt64(ParentId);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (UserId.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(UserId);
          }
          if (ParentId != 0L) {
            size += 1 + pb::CodedOutputStream.ComputeInt64Size(ParentId);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(EntityID other) {
          if (other == null) {
            return;
          }
          if (other.UserId.Length != 0) {
            UserId = other.UserId;
          }
          if (other.ParentId != 0L) {
            ParentId = other.ParentId;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
#else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                UserId = input.ReadString();
                break;
              }
              case 16: {
                ParentId = input.ReadInt64();
                break;
              }
            }
          }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                UserId = input.ReadString();
                break;
              }
              case 16: {
                ParentId = input.ReadInt64();
                break;
              }
            }
          }
        }
#endif

      }

    }
#endregion

  }

  /// <summary>
  //// - Mesh blocks (temporary hack)
  /// </summary>
  public sealed partial class MeshBlockEvent : pb::IMessage<MeshBlockEvent>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
#endif
  {
    private static readonly pb::MessageParser<MeshBlockEvent> _parser = new pb::MessageParser<MeshBlockEvent>(() => new MeshBlockEvent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MeshBlockEvent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Rho.Entities.Proto.EntityMsgsReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MeshBlockEvent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MeshBlockEvent(MeshBlockEvent other) : this() {
      anchorId_ = other.anchorId_;
      blockId_ = other.blockId_;
      position_ = other.position_ != null ? other.position_.Clone() : null;
      extent_ = other.extent_ != null ? other.extent_.Clone() : null;
      vertexData_ = other.vertexData_.Clone();
      indexData_ = other.indexData_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MeshBlockEvent Clone() {
      return new MeshBlockEvent(this);
    }

    /// <summary>Field number for the "anchor_id" field.</summary>
    public const int AnchorIdFieldNumber = 1;
    private ulong anchorId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong AnchorId {
      get { return anchorId_; }
      set {
        anchorId_ = value;
      }
    }

    /// <summary>Field number for the "block_id" field.</summary>
    public const int BlockIdFieldNumber = 2;
    private ulong blockId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong BlockId {
      get { return blockId_; }
      set {
        blockId_ = value;
      }
    }

    /// <summary>Field number for the "position" field.</summary>
    public const int PositionFieldNumber = 3;
    private global::Rho.Entities.Proto.MeshBlockEvent.Types.Vec3f position_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rho.Entities.Proto.MeshBlockEvent.Types.Vec3f Position {
      get { return position_; }
      set {
        position_ = value;
      }
    }

    /// <summary>Field number for the "extent" field.</summary>
    public const int ExtentFieldNumber = 4;
    private global::Rho.Entities.Proto.MeshBlockEvent.Types.Vec3f extent_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rho.Entities.Proto.MeshBlockEvent.Types.Vec3f Extent {
      get { return extent_; }
      set {
        extent_ = value;
      }
    }

    /// <summary>Field number for the "vertex_data" field.</summary>
    public const int VertexDataFieldNumber = 5;
    private static readonly pb::FieldCodec<float> _repeated_vertexData_codec
        = pb::FieldCodec.ForFloat(42);
    private readonly pbc::RepeatedField<float> vertexData_ = new pbc::RepeatedField<float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> VertexData {
      get { return vertexData_; }
    }

    /// <summary>Field number for the "index_data" field.</summary>
    public const int IndexDataFieldNumber = 6;
    private static readonly pb::FieldCodec<uint> _repeated_indexData_codec
        = pb::FieldCodec.ForUInt32(50);
    private readonly pbc::RepeatedField<uint> indexData_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> IndexData {
      get { return indexData_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MeshBlockEvent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MeshBlockEvent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AnchorId != other.AnchorId) return false;
      if (BlockId != other.BlockId) return false;
      if (!object.Equals(Position, other.Position)) return false;
      if (!object.Equals(Extent, other.Extent)) return false;
      if(!vertexData_.Equals(other.vertexData_)) return false;
      if(!indexData_.Equals(other.indexData_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (AnchorId != 0UL) hash ^= AnchorId.GetHashCode();
      if (BlockId != 0UL) hash ^= BlockId.GetHashCode();
      if (position_ != null) hash ^= Position.GetHashCode();
      if (extent_ != null) hash ^= Extent.GetHashCode();
      hash ^= vertexData_.GetHashCode();
      hash ^= indexData_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
#else
      if (AnchorId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(AnchorId);
      }
      if (BlockId != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(BlockId);
      }
      if (position_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Position);
      }
      if (extent_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Extent);
      }
      vertexData_.WriteTo(output, _repeated_vertexData_codec);
      indexData_.WriteTo(output, _repeated_indexData_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
    }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AnchorId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(AnchorId);
      }
      if (BlockId != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(BlockId);
      }
      if (position_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Position);
      }
      if (extent_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Extent);
      }
      vertexData_.WriteTo(ref output, _repeated_vertexData_codec);
      indexData_.WriteTo(ref output, _repeated_indexData_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
#endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (AnchorId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(AnchorId);
      }
      if (BlockId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(BlockId);
      }
      if (position_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Position);
      }
      if (extent_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Extent);
      }
      size += vertexData_.CalculateSize(_repeated_vertexData_codec);
      size += indexData_.CalculateSize(_repeated_indexData_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MeshBlockEvent other) {
      if (other == null) {
        return;
      }
      if (other.AnchorId != 0UL) {
        AnchorId = other.AnchorId;
      }
      if (other.BlockId != 0UL) {
        BlockId = other.BlockId;
      }
      if (other.position_ != null) {
        if (position_ == null) {
          Position = new global::Rho.Entities.Proto.MeshBlockEvent.Types.Vec3f();
        }
        Position.MergeFrom(other.Position);
      }
      if (other.extent_ != null) {
        if (extent_ == null) {
          Extent = new global::Rho.Entities.Proto.MeshBlockEvent.Types.Vec3f();
        }
        Extent.MergeFrom(other.Extent);
      }
      vertexData_.Add(other.vertexData_);
      indexData_.Add(other.indexData_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            AnchorId = input.ReadUInt64();
            break;
          }
          case 16: {
            BlockId = input.ReadUInt64();
            break;
          }
          case 26: {
            if (position_ == null) {
              Position = new global::Rho.Entities.Proto.MeshBlockEvent.Types.Vec3f();
            }
            input.ReadMessage(Position);
            break;
          }
          case 34: {
            if (extent_ == null) {
              Extent = new global::Rho.Entities.Proto.MeshBlockEvent.Types.Vec3f();
            }
            input.ReadMessage(Extent);
            break;
          }
          case 42:
          case 45: {
            vertexData_.AddEntriesFrom(input, _repeated_vertexData_codec);
            break;
          }
          case 50:
          case 48: {
            indexData_.AddEntriesFrom(input, _repeated_indexData_codec);
            break;
          }
        }
      }
#endif
    }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            AnchorId = input.ReadUInt64();
            break;
          }
          case 16: {
            BlockId = input.ReadUInt64();
            break;
          }
          case 26: {
            if (position_ == null) {
              Position = new global::Rho.Entities.Proto.MeshBlockEvent.Types.Vec3f();
            }
            input.ReadMessage(Position);
            break;
          }
          case 34: {
            if (extent_ == null) {
              Extent = new global::Rho.Entities.Proto.MeshBlockEvent.Types.Vec3f();
            }
            input.ReadMessage(Extent);
            break;
          }
          case 42:
          case 45: {
            vertexData_.AddEntriesFrom(ref input, _repeated_vertexData_codec);
            break;
          }
          case 50:
          case 48: {
            indexData_.AddEntriesFrom(ref input, _repeated_indexData_codec);
            break;
          }
        }
      }
    }
#endif

#region Nested types
    /// <summary>Container for nested types declared in the MeshBlockEvent message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public sealed partial class Vec3f : pb::IMessage<Vec3f>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
#endif
      {
        private static readonly pb::MessageParser<Vec3f> _parser = new pb::MessageParser<Vec3f>(() => new Vec3f());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Vec3f> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Rho.Entities.Proto.MeshBlockEvent.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Vec3f() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Vec3f(Vec3f other) : this() {
          x_ = other.x_;
          y_ = other.y_;
          z_ = other.z_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Vec3f Clone() {
          return new Vec3f(this);
        }

        /// <summary>Field number for the "x" field.</summary>
        public const int XFieldNumber = 1;
        private float x_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public float X {
          get { return x_; }
          set {
            x_ = value;
          }
        }

        /// <summary>Field number for the "y" field.</summary>
        public const int YFieldNumber = 2;
        private float y_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public float Y {
          get { return y_; }
          set {
            y_ = value;
          }
        }

        /// <summary>Field number for the "z" field.</summary>
        public const int ZFieldNumber = 3;
        private float z_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public float Z {
          get { return z_; }
          set {
            z_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Vec3f);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Vec3f other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(X, other.X)) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Y, other.Y)) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Z, other.Z)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (X != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(X);
          if (Y != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Y);
          if (Z != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Z);
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
#else
          if (X != 0F) {
            output.WriteRawTag(13);
            output.WriteFloat(X);
          }
          if (Y != 0F) {
            output.WriteRawTag(21);
            output.WriteFloat(Y);
          }
          if (Z != 0F) {
            output.WriteRawTag(29);
            output.WriteFloat(Z);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (X != 0F) {
            output.WriteRawTag(13);
            output.WriteFloat(X);
          }
          if (Y != 0F) {
            output.WriteRawTag(21);
            output.WriteFloat(Y);
          }
          if (Z != 0F) {
            output.WriteRawTag(29);
            output.WriteFloat(Z);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (X != 0F) {
            size += 1 + 4;
          }
          if (Y != 0F) {
            size += 1 + 4;
          }
          if (Z != 0F) {
            size += 1 + 4;
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Vec3f other) {
          if (other == null) {
            return;
          }
          if (other.X != 0F) {
            X = other.X;
          }
          if (other.Y != 0F) {
            Y = other.Y;
          }
          if (other.Z != 0F) {
            Z = other.Z;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
#else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 13: {
                X = input.ReadFloat();
                break;
              }
              case 21: {
                Y = input.ReadFloat();
                break;
              }
              case 29: {
                Z = input.ReadFloat();
                break;
              }
            }
          }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 13: {
                X = input.ReadFloat();
                break;
              }
              case 21: {
                Y = input.ReadFloat();
                break;
              }
              case 29: {
                Z = input.ReadFloat();
                break;
              }
            }
          }
        }
#endif

      }

    }
#endregion

  }

  public sealed partial class MeshBlockEvents : pb::IMessage<MeshBlockEvents>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
#endif
  {
    private static readonly pb::MessageParser<MeshBlockEvents> _parser = new pb::MessageParser<MeshBlockEvents>(() => new MeshBlockEvents());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MeshBlockEvents> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Rho.Entities.Proto.EntityMsgsReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MeshBlockEvents() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MeshBlockEvents(MeshBlockEvents other) : this() {
      meshBlockEvent_ = other.meshBlockEvent_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MeshBlockEvents Clone() {
      return new MeshBlockEvents(this);
    }

    /// <summary>Field number for the "mesh_block_event" field.</summary>
    public const int MeshBlockEventFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Rho.Entities.Proto.MeshBlockEvent> _repeated_meshBlockEvent_codec
        = pb::FieldCodec.ForMessage(10, global::Rho.Entities.Proto.MeshBlockEvent.Parser);
    private readonly pbc::RepeatedField<global::Rho.Entities.Proto.MeshBlockEvent> meshBlockEvent_ = new pbc::RepeatedField<global::Rho.Entities.Proto.MeshBlockEvent>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Rho.Entities.Proto.MeshBlockEvent> MeshBlockEvent {
      get { return meshBlockEvent_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MeshBlockEvents);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MeshBlockEvents other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!meshBlockEvent_.Equals(other.meshBlockEvent_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= meshBlockEvent_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
#else
      meshBlockEvent_.WriteTo(output, _repeated_meshBlockEvent_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
    }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      meshBlockEvent_.WriteTo(ref output, _repeated_meshBlockEvent_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
#endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += meshBlockEvent_.CalculateSize(_repeated_meshBlockEvent_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MeshBlockEvents other) {
      if (other == null) {
        return;
      }
      meshBlockEvent_.Add(other.meshBlockEvent_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            meshBlockEvent_.AddEntriesFrom(input, _repeated_meshBlockEvent_codec);
            break;
          }
        }
      }
#endif
    }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            meshBlockEvent_.AddEntriesFrom(ref input, _repeated_meshBlockEvent_codec);
            break;
          }
        }
      }
    }
#endif

  }

#endregion

}

#endregion Designer generated code

#endif